@extends('layouts.app')

@section('title', 'Reports')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h2 class="fw-bold text-dark">Reports</h2>
                <a href="{{ route('reports.create') }}" class="btn btn-primary">
                    <i class="fas fa-plus me-2"></i>Generate New Report
                </a>
            </div>

            @if(session('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ session('success') }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                </div>
            @endif

            @if(session('info'))
                <div class="alert alert-info alert-dismissible fade show" role="alert">
                    {{ session('info') }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                </div>
            @endif

            <div class="card shadow-sm">
                <div class="card-body">
                    @if($reports->count() > 0)
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead class="table-light">
                                    <tr>
                                        <th>Report Number</th>
                                        <th>Student</th>
                                        <th>Term</th>
                                        <th>Academic Year</th>
                                        <th>Type</th>
                                        <th>Generated By</th>
                                        <th>Generated At</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($reports as $report)
                                        <tr>
                                            <td>
                                                <span class="fw-bold text-primary">{{ $report->report_number }}</span>
                                            </td>
                                            <td>
                                                <div class="fw-bold">{{ $report->student->name }}</div>
                                                <small class="text-muted">{{ $report->student->student_number }}</small>
                                            </td>
                                            <td>{{ $report->term }}</td>
                                            <td>{{ $report->academic_year }}</td>
                                            <td>
                                                <span class="badge bg-info">
                                                    {{ ucwords(str_replace('_', ' ', $report->report_type)) }}
                                                </span>
                                            </td>
                                            <td>{{ $report->generatedBy->name }}</td>
                                            <td>{{ $report->generated_at->format('M d, Y g:i A') }}</td>
                                            <td>
                                                <div class="btn-group" role="group">
                                                    <a href="{{ route('reports.show', $report) }}" 
                                                       class="btn btn-sm btn-outline-info" title="View">
                                                        <i class="fas fa-eye"></i>
                                                    </a>
                                                    <a href="{{ route('reports.print', $report) }}" 
                                                       class="btn btn-sm btn-outline-success" title="Print" target="_blank">
                                                        <i class="fas fa-print"></i>
                                                    </a>
                                                    <form action="{{ route('reports.destroy', $report) }}" 
                                                          method="POST" class="d-inline"
                                                          onsubmit="return confirm('Are you sure you want to delete this report?')">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-sm btn-outline-danger" title="Delete">
                                                            <i class="fas fa-trash"></i>
                                                        </button>
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>

                        <div class="d-flex justify-content-center mt-4">
                            {{ $reports->links() }}
                        </div>
                    @else
                        <div class="text-center py-5">
                            <i class="fas fa-file-alt fa-3x text-muted mb-3"></i>
                            <h5 class="text-muted">No reports found</h5>
                            <p class="text-muted">Generate your first report to get started.</p>
                            <a href="{{ route('reports.create') }}" class="btn btn-primary">
                                <i class="fas fa-plus me-2"></i>Generate Report
                            </a>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection